#!/usr/bin/env bash
makoctl dismiss -a || swaync-client -C

songname=$(mpc current)
playpause=$(mpc status %state%)

if [ "$playpause" = "paused" ]; then
	status=" "
else
	status=" "
fi

notify-send "$status $songname"
