#!/usr/bin/env bash
makoctl dismiss -a

songname=$(basename "$(mpc current | sed "-e s/ /_/g")" | sed -e "s/_/ /g" -e "s/.mp3//g")
playpause=$(mpc status %state%)

if [ "$playpause" = "paused" ]; then
	status=" "
else
	status=" "
fi

notify-send "$status $songname"
