#!/bin/env bash

if [[ "$1" ]]; then
	prompt="$1"
	echo "prompt: $prompt"
else
	echo prompt:
	read -r prompt
fi

raw=$(curl https://free.churchless.tech/v1/chat/completions \
	-s \
	-H 'Content-Type: application/json' \
	-d '{
"model": "gpt-3.5-turbo",
"messages": [{"role": "user", "content":"'"$prompt"'"}]
}')

answer=$(echo $raw | grep -oP '(?<="content":")[^"]*')
if [[ -z $answer ]]; then
	echo "$raw"
	echo there has been an error
	exit 1
fi

echo "assistant: $answer"
