#!/bin/python3
import random as rn
import numpy as np
import operator

quantity = int(input("How many options are there?\n: "))
results = {}
power_levels = np.array([])
for i in range(1, quantity+1):
    power = rn.random()
    results.update({i:power})

sorted_results = sorted(results.items(), key=operator.itemgetter(1))
final_results = [i[0] for i in sorted_results]
print(final_results[-1], "Is absolutely what you're looking for, but here's the rest in order:")
for i in final_results[:-2]:
    print(i, end="; ")
print(final_results[-2])
