#!/usr/bin/env bash
# originally by Kris Occhipinti
# https://www.youtube.com/watch?v=FsQuGplQvrw

if [[ $1 ]]; then
	notify-send -t 3000 "Playing Video" "$1"
	hyprctl dispatch exec "[floating:1;pin;size: 40% 40%;move 59% 5%] mpv --ytdl-format=bestvideo+bestaudio/best --speed=1 $1"
else
	notify-send -t 3000 "Playing Video" "$(wl-paste)"
	hyprctl dispatch exec "[floating:1;pin;size: 40% 40%;move 59% 5%] mpv --ytdl-format=bestvideo+bestaudio/best --speed=1 $(wl-paste)"
fi
