#!/usr/bin/env bash
if pgrep remouse; then
	kill $(pgrep remouse)
	notify-send "remouse terminated"
else
	# hyprctl dispatch exec "[floating:1] remouse --evdev --region"
	remouse --evdev
	notify-send "starting remouse"
fi
