#!/usr/bin/env bash

cat >>flake.nix <<EOF
{
    description = "devFlake for $(basename "$(pwd)")";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
  };

  outputs = {nixpkgs, ...}: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.\${system};
  in {
    devShells.\${system} = {
      default = pkgs.mkShell {
        buildInputs = with pkgs; [
          fish
        ];
        shellHook = ''
          export SHELL=\${pkgs.fish}/bin/fish
          exec fish
        '';
      };
    };
  };
}
EOF
