#!/bin/sh
riverctl background-color "0x44418c"
riverctl border-color-focused "0x645fcb"
riverctl border-color-unfocused "0x44418c"

killall swaybg
swaybg -i ~/.config/wpg/.current &
waybar-restart &
killall mako
mako &
