#!/bin/sh
riverctl background-color "0x2c3814"
riverctl border-color-focused "0x40531d"
riverctl border-color-unfocused "0x2c3814"

killall swaybg
swaybg -i ~/.config/wpg/.current &
waybar-restart &
killall mako
mako &
