#!/bin/sh
riverctl background-color "0x8c5266"
riverctl border-color-focused "0xcb7794"
riverctl border-color-unfocused "0x8c5266"

killall swaybg
swaybg -i ~/.config/wpg/.current &
waybar-restart &
killall mako
mako &
