#!/usr/bin/env bash

# This script does the following:
#	Run by itself, set the wallpaper (at X start).
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.
#	If wal is installed, also generates a colorscheme.

# Location of link to wallpaper link.
bgloc="${XDG_CONFIG_HOME:-$HOME/.config/}/bg"

# Configuration files of applications that have their themes changed by pywal.
dunstconf="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc"
zathuraconf="${XDG_CONFIG_HOME:-$HOME/.config}/zathura/zathurarc"

trueloc="$(readlink -f "$1")" &&
	case "$(file --mime-type -b "$trueloc")" in
	image/*) ln -sf "$(readlink -f "$1")" "$bgloc" && notify-send -i "$bgloc" "Changing wallpaper..." ;;
	inode/directory) ln -sf "$(find "$trueloc" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" && notify-send -i "$bgloc" "Random Wallpaper chosen." ;;
	*)
		notify-send "Error" "Not a valid image."
		exit 1
		;;
	esac

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
	swaybg -i "$bgloc" &
else
	xwallpaper --zoom "$bgloc"
fi
