#!/usr/bin/env bash
if pidof wlsunset; then
	makoctl dismiss -a
	notify-send "Night Mode Off"
	killall wlsunset
else
	makoctl dismiss -a
	notify-send "Night Mode On"
	wlsunset -l 44.5 -L 11.33 -t 1900 -T 6500
fi
