#!/usr/bin/env bash

echo -en "write your commit message\n   : "
read -r message
if [[ ! $message ]]; then
	message="update"
fi

git add .
git commit -am "$message"

echo -en "Push?(N/yes)"
read -r push
if [[ $push = "yes" ]]; then
    git push
fi
