#!/bin/sh

WORD="$(rofi -dmenu -p "Search:")"

TESTWORD="$(dym -c -n=1 "$WORD")"

if [ "$WORD" != "$TESTWORD" ]; then
	KEYWORD=$(dym -c "$WORD" | rofi -dmenu -p "was $WORD a misspelling?(select/no)")
	if [ "$KEYWORD" = "no" ] || [ "$KEYWORD" = "n" ]; then
		KEYWORD="$WORD"
	fi
else
	KEYWORD="$WORD"
fi

if ! [ "${KEYWORD}" ]; then
	printf 'No word inserted\n' >&2
	exit 0
fi

tempfile=/tmp/wikipedia.txt
whats "$KEYWORD" >>"$tempfile"
"$TERMINAL" -e "$EDITOR" "$tempfile"
rm "$tempfile"
