#!/usr/bin/env bash
setbg ~/.config/wpg/.current
if pgrep waybar; then
	waybar-restart &
fi
restart mako
if pgrep river; then
	river-theme
fi
notify-send -i "$HOME"/.config/wpg/.current "Changing theme..."
