#!/usr/bin/env bash
setbg ~/.config/wpg/.current
sleep 2
if pgrep waybar; then
	waybar-restart &
fi
if pgrep gBar; then
	sass ~/.config/gBar/style.scss >~/.config/gBar/style.css
	killall gBar
	gBar bar 0 &
fi
makoctl reload
if pgrep river; then
	river-theme
fi
notify-send -i "$HOME"/.config/wpg/.current "Changing theme..."
if pgrep spotify; then
	echo "yeah"
	spicetify apply && spotify
else
	spicetify apply
fi
