#!/usr/bin/env bash
rofi_command="rofi -theme $HOME/.config/rofi/modules/tools_menu.rasi"

# Icons
color_picker=" Color Picker"
logout_tool=" Logout"
reload_hypr=" Reload"

options="$color_picker\n$logout_tool\n$reload_hypr"

chosen="$(echo -e "$options" | $rofi_command -p " Useful Tools" -dmenu -selected-row 1)"

case $chosen in
    $color_picker)
        grim -g "$(~/.config/hypr/scripts/slurp_window.sh) 1x1" -t ppm - | convert - -format '\#%[hex:u.p{0,0}]' info: | wl-copy
        ;;
    $logout_tool)
        pkill -9 -u $USER
        ;;
    $reload_hypr)
        hyprctl reload
        ;;
esac



# Use grim and slurp and imagemagick to get the hex code of a pixel

