#!/usr/bin/env bash
#
# Script name: dm-gpt
# Description: Search an offline copy of the Arch Wiki.
# Dependencies: dmenu, arch-wiki-docs
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor, marvhus

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main ()
{
  raw_query=$(${DMENU} "what's your question?")
  query='"'"$raw_query"'"'
  answer=$(gpt-query "$query")
  echo $answer
  echo $answer | wl-copy
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
