#!/usr/bin/env bash
#
# Script name: dm-documents
# Description: Search for a process to kill.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor, HostGrady

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.

set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[ -f "${_path}/_dm-helper.sh" ]]; then
	# shellcheck disable=SC1090,SC1091
	source "${_path}/_dm-helper.sh"
else
	# shellcheck disable=SC1090
	echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
	files="$(find "$HOME" -maxdepth 5 -iname "*.png")"
	choice=$(printf '%s\n' "${files[@]}" |
		cut -d '/' -f4- |
		sed -e 's/Documents/Dcs/g' \
			-e 's/Downloads/Dwn/g' \
			-e 's/.local/lcl/g' \
			-e 's/Pictures/Pic/g' \
			-e 's/Images/Img/g' \
			-e 's/.png//g' |
		sort -g |
		${DMENU} "File: " "$@") || exit 1
	if [ "$choice" ]; then
		file=$(
			printf '%s' "$choice" |
				sed -e 's/Dcs/Documents/g' \
					-e 's/Dwn/Downloads/g' \
					-e 's/lcl/.local/g' \
					-e 's/Pic/Pictures/g' \
					-e 's/Img/Images/g'
		)
		dragon "$HOME/${file}.png"
	else
		echo "Program Terminated." && exit 0
	fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
