#!/usr/bin/env bash

# assist: repeat a given text n times

TEXT="$(echo test | fuzzel --dmenu -p 'spam text')"
[ -n "$TEXT" ] || exit

LOOP="$(echo 10 | fuzzel --dmenu -p 'repeat')"
[ -n "$LOOP" ] || exit

if ! [ "$LOOP" -eq "$LOOP" ]; then
	LOOP=10
fi

sleep 1

for _ in $(seq 1 $LOOP); do
	wtype "$TEXT" -P KP_Enter
done
