#!/usr/bin/env bash

# The famous "get a menu of emojis to copy" script.

# Get user selection via rofi -dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/scripts_helpers/emojis | rofi -dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command without an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ ! "$1" ]; then
	wtype "$chosen"
else
	printf "$chosen" | wl-copy
	notify-send "'$chosen' copied to clipboard." &
fi
