#!/usr/bin/env bash
name=$(rofi -dmenu -p "instert name")
touch "$HOME"/.local/src/paste-images/"$name".png
wl-paste >"$HOME"/.local/src/paste-images/"$name".png
cd "$HOME"/.local/src/paste-images/ >/dev/null || exit 1
update-git &>/dev/null
echo "($name)[https://github.com/soliprem/paste-images/$name.png]"
